= Red Hat Summit OptaPlanner

== Build & run using Spring Boot

`mvn spring-boot:run`

To run with the Infinispan connector:

1. Run infinispan server (make sure counters and DispatchEvents caches are added to the config file):

    $INFINISPAN_HOME/bin/standalone.sh -c CONFIG_FILE.xml

2. Change hotrod endpoint in `hotrod-client.properties`:

    infinispan.client.hotrod.endpoint=localhost

3. Run the application:

    `mvn spring-boot:run -Dprod`

== Build & run on OpenShift

1. Login to a running OpenShift instance

    oc login -u USERNAME -p PASSWORD OPENSHIFT_URL

2. Make sure datagrid service is running, if not deploy it:

    git clone git@github.com:rhdemo/2019-demo4-cluster-setup.git
    ./2019-demo4-cluster-setup/datagrid/deploy.sh

3. Either use an existing project or create a new one by executing:

    oc new-project NAME

3. Deploy the application to the project

    mvn clean package -Popenshift

4. Find out a URL the service was exposed on

    oc get route

== Infinispan relevant data

Below are examples on key/value pairs in Infinispan caches that are relevant to OptaPlanner.

=== Cache `DispatchMechanic`

```
MECHANIC_ID: {
    responseType: "DISPATCH_MECHANIC" or "ADD_MECHANIC",
    mechanic: {
        "mechanicIndex": 0,
        “originalMachineIndex”: 0,
        "focusMachineIndex": 0,
        "focusTravelDurationMillis": 1000,
        "focusFixDurationMillis": 2000
    }
}
```

```
MECHANIC_ID-futureIndexes: {
    responseType: "UPDATE_FUTURE_VISITS",
    mechanicIndex: 0,
    futureMachineIndexes: [
        0,
        1,
        ...
    ]
}
```

=== Cache `default`
```
OptaPlannerConfig: {
    dispatchActive: true/false,
    simulationActive: true/false
}
```
